### ISSUE TITLE
Simple Question: What does "prop" mean in the plots?

### ISSUE THREAD

**Issue by bryanhanson** [mlr-org/ParamHelpers#225]
I see in the code that the final point in an optimization is labeled "prop".  What does this stand for?

**Comment by mb706** [comment]
Best I can think of is "proposition", maybe someone else here knows better.

**Comment by bryanhanson** [comment]
I was thinking "proposed" as in a final answer, but at least in my use case the last one has never been the best answer, which is part of what led me to ask.

**Comment by jakob-r** [comment]
Can you give me some context?

**Comment by bryanhanson** [comment]
It’s the label given to the last dob point and marked in green on plots.

**Comment by jakob-r** [comment]
Are you talking about `plotOptPath()` and 'renderOptPathPlot()`?
In this case the *newest* point will always be marked as **prop**osal. As such is it is not the proposal of the best point but the point that is proposed by the optimization algorithm in the most recent iteration.
Do you think we should document this better?

**Comment by bryanhanson** [comment]
Thank you Jakob-r, yes, the newest point.  I understand how you are using the term now.  I can see how in code one would keep track of the current or proposed point.  Is it important to mark it in the plot though?  It is always the most recent point (if I understand correctly) if plotting against DOB.

You have developed a great set of packages that I am finding very useful, and one of the strengths is the diverse set of learners and parameters one can use.  I only know reasonably well the little piece I am using (see my [blog post](https://chemospec.org/2020/02/20/p8/) about one application).  Given the range of applications I don't know if marking the proposed point in plots is generally useful or not. So my question is answered, I leave it to you to think about the value in marking the point or not.

I do think it should be documented -- a very short vignette about the plots would be a nice addition.  I had to look through your code to figure out what DOB was (very clever name though!).

Thanks for your time and effort on this.  I'll let you close the issue unless there is more to say.

**Comment by jakob-r** [comment]
I will close this issue. I hope we make plots more clear in our future packages.
